# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7981b7a5c61c3d9128a66277fbcc4cb91d7ecebe46399e631cd5811bc537c7534ba79a8274a172feb900d3d9f20df697ad8d0aea610229f29c6b35aa665ec493

test:
  secret_key_base: 73dd9b94cce8497e69c3d1f873e9f6a89f9c44f225e07def81bcfa5b7a8c1e8f21aefc8e6cb6a731acd582b990b2a1ba0bf3e0b4a4fd90b96f0ba47bbef5676d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
